Geoserver/gtfs-api: only cast route_type explicitly
mobidata-bw/ipl-orchestration pull request #116
Opened 2024-04-03 09:15 UTC by derhuerst

This *might be* a breaking change, because we remove the ability to implicitly cast `route_type_val` to `integer`.

I checked the use case documented in #113 and `gtfs-api`'s filtering (using `curl 'http://localhost:4000/routes?route_type=eq.3&limit=1' -H 'Accept: application/json' -fsSL`), and both seem to work fine. @hbruch Can you think of more cases and queries which this change may break?

---

fixes https://github.com/mobidata-bw/ipl-orchestration/issues/113

2024-04-09 09:03 UTC, richardforsterNVBW commented
So far this bug fix hasn't been merged. Is there still a test to go?

2024-04-09 13:56 UTC, hbruch requested changes
I expect this won't fix the cql issues.

2024-04-10 21:21 UTC, derhuerst commented
> I expect this won't fix the cql issues.

I wouldn't *expect* that either, but apparently it does. 🤔 – I tried this PR together with #107, and the `route_type = 3 OR route_type = 2` filter works.

2024-04-17 16:40 UTC, hbruch commented
Did you try this via psql or via geoserver? After reimporting locally with this PR, I still see these errors:
<img width="1000" alt="image" src="https://github.com/mobidata-bw/ipl-orchestration/assets/2187389/d573d2cf-e2bd-4b6b-9c45-4bfdba8d24aa">

```sql 
gtfs_1713370646=# select * from geoserver.shapes_with_routes where route_type=2 limit 0;
 shape_id | shape | route_type | route_ids | route_names
----------+-------+------------+-----------+-------------
(0 rows)

gtfs_1713370646=# select * from geoserver.shapes_with_routes where route_type='2' limit 0;
 shape_id | shape | route_type | route_ids | route_names
----------+-------+------------+-----------+-------------
(0 rows)

gtfs_1713370646=# select * from geoserver.shapes_with_routes where route_type='2' or route_type='3' limit 0;
 shape_id | shape | route_type | route_ids | route_names
----------+-------+------------+-----------+-------------
(0 rows)

gtfs_1713370646=# select * from geoserver.shapes_with_routes where route_type in ('2','3') limit 0;
ERROR:  operator is not unique: api.route_type_val = api.route_type_val
LINE 1: ...rom geoserver.shapes_with_routes where route_type in ('2','3...
                                                             ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
```

2024-04-21 16:11 UTC, derhuerst commented
> Did you try this via psql or via geoserver? After reimporting locally with this PR, I still see these errors: [...]

Aha, this image shows `route_type eq 3 OR route_type eq 2, and I tried with `route_type = 3 OR route_type = 2`.

2024-04-21 19:43 UTC, hbruch commented
Ooh, you are right 🙈

2024-04-26 07:46 UTC, hbruch approved these changes
Approved, as using `=` instead of `eq` works.

2024-04-26 15:33 UTC, merged